"""Create .env.production with fresh secrets, a new model-signing key pair and signed production weights.

Usage (from backend/):
    python scripts/make_production_env.py            # refuses to overwrite an existing .env.production
    python scripts/make_production_env.py --resign   # only copy + re-sign weights (after new training)

What it does:
  * writes <repo>/.env.production with new random values for the JWT secret, the AES-256-GCM key ring,
    the audit-anchor HMAC key, the model-signing password and the MongoDB root password
    (the secrets are never printed);
  * no DEMO_* accounts: create the real admin with scripts/create_admin.py;
  * keeps production keys, weights, storage and logs in their own folders
    (backend/keys-production, weights-production, storage-production, logs-production),
    so the demo setup in .env keeps working unchanged;
  * copies the current weights into weights-production and signs them with the NEW key.
Run it on the machine that will serve the app. Back up .env.production and backend/keys-production:
losing them means encrypted data can no longer be read.
"""
import argparse
import os
import secrets
import shutil
import subprocess
import sys

BACKEND = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ROOT = os.path.dirname(BACKEND)
ENV_PATH = os.path.join(ROOT, ".env.production")
DIRS = {name: os.path.join(BACKEND, f"{name}-production") for name in ("keys", "weights", "storage", "logs")}
COPY_SUFFIXES = (".pt", ".pkl", ".json")


def copy_weights() -> int:
    src, dst = os.path.join(BACKEND, "weights"), DIRS["weights"]
    n = 0
    for dirpath, _dirs, files in os.walk(src):
        for f in files:
            if f.startswith("manifest.json") or not f.endswith(COPY_SUFFIXES):
                continue
            rel = os.path.relpath(os.path.join(dirpath, f), src)
            os.makedirs(os.path.dirname(os.path.join(dst, rel)), exist_ok=True)
            shutil.copy2(os.path.join(dirpath, f), os.path.join(dst, rel))
            n += 1
    return n


def sign_model(*args) -> None:
    env = {**os.environ, "ENV_FILE": ENV_PATH}
    for k in ("KEYS_DIR", "WEIGHTS_DIR", "MODEL_SIGNING_PASSWORD", "DB_MODE"):
        env.pop(k, None)                       # take them from .env.production only
    subprocess.run([sys.executable, os.path.join(BACKEND, "scripts", "sign_model.py"), *args], cwd=BACKEND, env=env, check=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--resign", action="store_true", help="only refresh and re-sign weights-production")
    args = ap.parse_args()

    if args.resign:
        if not os.path.exists(ENV_PATH):
            print("ERROR: .env.production does not exist yet; run without --resign first.")
            return 2
        print(f"copied {copy_weights()} weight/metadata files into weights-production")
        sign_model()
        sign_model("--verify")
        return 0

    if os.path.exists(ENV_PATH):
        print("ERROR: .env.production already exists. Refusing to overwrite it (the old keys would be lost).")
        return 2
    for d in DIRS.values():
        os.makedirs(d, exist_ok=True)
    if os.listdir(DIRS["keys"]):
        print(f"ERROR: {DIRS['keys']} is not empty. Refusing to replace existing production keys.")
        return 2

    hexkey = lambda: secrets.token_hex(32)  # noqa: E731  (256-bit)
    mongo_pw = secrets.token_urlsafe(24)       # URL-safe characters only, so it can sit inside MONGO_URI
    values = {
        "DB_MODE": "production",
        "MONGO_URI": f"mongodb://periovision_admin:{mongo_pw}@localhost:27017/periovision_db?authSource=admin",
        "DB_NAME": "periovision_db",
        "MONGO_ROOT_USER": "periovision_admin",
        "MONGO_ROOT_PASSWORD": mongo_pw,
        "PORT": "5000",
        "FLASK_DEBUG": "0",
        "PUBLIC_BASE_URL": "http://127.0.0.1:5000",
        "CORS_ORIGINS": "http://localhost:4173,http://127.0.0.1:4173",
        "PUBLIC_VERIFY_URL": "http://localhost:4173/verify",
        "REDIS_URL": "memory://",
        "JWT_SECRET_KEY": hexkey(),
        "ACCESS_TOKEN_MINUTES": "15",
        "REFRESH_TOKEN_DAYS": "7",
        "SESSION_IDLE_MINUTES": "30",
        "FIELD_ENCRYPTION_KEYS": f"k1:{hexkey()}",
        "FIELD_ENCRYPTION_ACTIVE_KID": "k1",
        "AUDIT_ANCHOR_KEY": hexkey(),
        "MODEL_SIGNING_PASSWORD": secrets.token_urlsafe(32),
        "KEYS_DIR": DIRS["keys"],
        "WEIGHTS_DIR": DIRS["weights"],
        "STORAGE_DIR": DIRS["storage"],
        "LOGS_DIR": DIRS["logs"],
        "USE_AWS_SECRETS": "false",
        "TLS_CERT": "",
        "TLS_KEY": "",
    }
    lines = [
        "# PerioVision AI - PRODUCTION settings. Generated by backend/scripts/make_production_env.py.",
        "# Contains live secrets: never commit, share or paste this file. Back it up together with backend/keys-production.",
        "# Use it with:  .\\run.ps1 prod   (sets ENV_FILE=.env.production)",
        "# After choosing a domain (deployment step 4), set PUBLIC_BASE_URL, CORS_ORIGINS and PUBLIC_VERIFY_URL to it.",
        "# There are deliberately no DEMO_* accounts. Create the real admin with: .\\run.ps1 create-admin",
        "",
    ] + [f"{k}={v}" for k, v in values.items()]
    with open(ENV_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {ENV_PATH} (secrets not shown)")
    print(f"copied {copy_weights()} weight/metadata files into weights-production")
    sign_model("--init-keys")
    sign_model()
    sign_model("--verify")
    print("Done. Next: start MongoDB, then .\\run.ps1 create-admin and .\\run.ps1 prod")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
